project_id = "pypkjchxhgjbzgkyskhj"

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.paypal-config]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false

[functions.generateQuestionsWithResearch]
verify_jwt = false
